export const GREEK_CITIES = {
  Athens: "Athens",
  Thessaloniki: "Thessaloniki",
  Patras: "Patras",
  Piraeus: "Piraeus",
  Heraklion: "Heraklion",
  Larissa: "Larissa",
  Volos: "Volos",
  Peristeri: "Peristeri",
  Acharnes: "Acharnes",
  Kallithea: "Kallithea",
  Kalamaria: "Kalamaria",
  Glyfada: "Glyfada",
  Nikaia: "Nikaia",
  Ilion: "Ilion",
  Evosmos: "Evosmos",
  Chalandri: "Chalandri",
  Ilioupoli: "Ilioupoli",
  Keratsini: "Keratsini",
  NeaSmyrni: "NeaSmyrni",
  Marousi: "Marousi",
  AgiosDimitrios: "AgiosDimitrios",
  Zografou: "Zografou",
  Egaleo: "Egaleo",
  Ioannina: "Ioannina",
  PalaioFaliro: "PalaioFaliro",
  NeaIonia: "NeaIonia",
  Chalcis: "Chalcis",
  AgiaParaskevi: "AgiaParaskevi",
  Trikala: "Trikala",
  Korydallos: "Korydallos",
  Petroupoli: "Petroupoli",
  Alexandroupoli: "Alexandroupoli",
  Serres: "Serres",
  Katerini: "Katerini",
  Vyronas: "Vyronas",
  Kalamata: "Kalamata",
  Xanthi: "Xanthi",
  Galatsi: "Galatsi",
  Rhodes: "Rhodes",
  Chania: "Chania",
  Komotini: "Komotini",
  Kavala: "Kavala",
  Agrinio: "Agrinio",
  Irakleio: "Irakleio",
  Kifissia: "Kifissia",
  Lamia: "Lamia",
  Chaidari: "Chaidari",
  Stavroupoli: "Stavroupoli",
  Drama: "Drama",
  Kozani: "Kozani",
  Veria: "Veria",
  Alimos: "Alimos",
  Karditsa: "Karditsa",
  Polichni: "Polichni",
  Pylaia: "Pylaia",
  Ampelokipoi: "Ampelokipoi",
  Rethymno: "Rethymno",
  Sykies: "Sykies",
  AnoLiosia: "AnoLiosia",
  Gerakas: "Gerakas",
  Mytilene: "Mytilene",
  Argyroupoli: "Argyroupoli",
  Vrilissia: "Vrilissia",
  AgioiAnargyroi: "AgioiAnargyroi",
  Ptolemaida: "Ptolemaida",
  Voula: "Voula",
  Aspropyrgos: "Aspropyrgos",
  Cholargos: "Cholargos",
  Koropi: "Koropi",
  Corinth: "Corinth",
  Corfu: "Corfu",
  Giannitsa: "Giannitsa",
  Tripoli: "Tripoli",
  Metamorfosi: "Metamorfosi",
  Kamatero: "Kamatero",
  Megara: "Megara",
  Chios: "Chios",
  AgiaVarvara: "AgiaVarvara",
  Kaisariani: "Kaisariani",
  EleftherioKordelio: "EleftherioKordelio",
  Pyrgos: "Pyrgos",
  Neapoli: "Neapoli",
  Perama: "Perama",
  Moschato: "Moschato",
  NeaFiladelfeia: "NeaFiladelfeia",
  Salamina: "Salamina",
  Eleusis: "Eleusis",
  Kilkis: "Kilkis",
  Arta: "Arta",
  Oraiokastro: "Oraiokastro",
  Melissia: "Melissia",
  Pallini: "Pallini",
  Dafni: "Dafni",
  Livadeia: "Livadeia",
  Artemida: "Artemida",
  Argos: "Argos",
  Thebes: "Thebes",
  Kos: "Kos",
  Pefki: "Pefki",
  Preveza: "Preveza",
  Aigio: "Aigio",
  Orestiada: "Orestiada",
  Thermi: "Thermi",
  NeaErythraia: "NeaErythraia",
  Amaliada: "Amaliada",
  NeaMakri: "NeaMakri",
  Naousa: "Naousa",
  Edessa: "Edessa",
  Sparta: "Sparta",
  Kalymnos: "Kalymnos",
  Ierapetra: "Ierapetra",
  Panorama: "Panorama",
  Florina: "Florina",
  Peraia: "Peraia",
  Vari: "Vari",
  Elliniko: "Elliniko",
  Kastoria: "Kastoria",
  Gazi: "Gazi",
  Paiania: "Paiania",
  Alexandreia: "Alexandreia",
  KalyviaThorikou: "KalyviaThorikou",
  Efkarpia: "Efkarpia",
  AgiosIoannisRenti: "AgiosIoannisRenti",
  Rafina: "Rafina",
  Nafplio: "Nafplio",
  Tavros: "Tavros",
  Menemeni: "Menemeni",
  Missolonghi: "Missolonghi",
  Papagou: "Papagou",
  Loutraki: "Loutraki",
  Drapetsona: "Drapetsona",
  AgiosNikolaos: "AgiosNikolaos",
  Pefka: "Pefka",
  NeaAlikarnassos: "NeaAlikarnassos",
  Spata: "Spata",
  Nafpaktos: "Nafpaktos",
  Ialysos: "Ialysos",
  Grevena: "Grevena",
  Mandra: "Mandra",
  GlykaNera: "GlykaNera",
  Diavata: "Diavata",
  Tyrnavos: "Tyrnavos",
  Sitia: "Sitia",
  Ermoupoli: "Ermoupoli",
  Argostoli: "Argostoli",
  NeoPsychiko: "NeoPsychiko",
  AgiosStefanos: "AgiosStefanos",
  Ymittos: "Ymittos",
  Anatoli: "Anatoli",
  Igoumenitsa: "Igoumenitsa",
  NeaArtaki: "NeaArtaki",
  NeaMoudania: "NeaMoudania",
} as const;

// Greek display names for the dropdown
export const GREEK_CITY_DISPLAY_NAMES: Record<keyof typeof GREEK_CITIES, string> = {
  Athens: "Αθήνα",
  Thessaloniki: "Θεσσαλονίκη",
  Patras: "Πάτρα",
  Piraeus: "Πειραιάς",
  Heraklion: "Ηράκλειο",
  Larissa: "Λάρισα",
  Volos: "Βόλος",
  Peristeri: "Περιστέρι",
  Acharnes: "Αχαρνές",
  Kallithea: "Καλλιθέα",
  Kalamaria: "Καλαμαριά",
  Glyfada: "Γλυφάδα",
  Nikaia: "Νίκαια",
  Ilion: "Ίλιον",
  Evosmos: "Εύοσμος",
  Chalandri: "Χαλάνδρι",
  Ilioupoli: "Ηλιούπολη",
  Keratsini: "Κερατσίνι",
  NeaSmyrni: "Νέα Σμύρνη",
  Marousi: "Μαρούσι",
  AgiosDimitrios: "Άγιος Δημήτριος",
  Zografou: "Ζωγράφου",
  Egaleo: "Αιγάλεω",
  Ioannina: "Ιωάννινα",
  PalaioFaliro: "Παλαιό Φάληρο",
  NeaIonia: "Νέα Ιωνία",
  Chalcis: "Χαλκίδα",
  AgiaParaskevi: "Αγία Παρασκευή",
  Trikala: "Τρίκαλα",
  Korydallos: "Κορυδαλλός",
  Petroupoli: "Πετρούπολη",
  Alexandroupoli: "Αλεξανδρούπολη",
  Serres: "Σέρρες",
  Katerini: "Κατερίνη",
  Vyronas: "Βύρωνας",
  Kalamata: "Καλαμάτα",
  Xanthi: "Ξάνθη",
  Galatsi: "Γαλάτσι",
  Rhodes: "Ρόδος",
  Chania: "Χανιά",
  Komotini: "Κομοτηνή",
  Kavala: "Καβάλα",
  Agrinio: "Αγρίνιο",
  Irakleio: "Ηράκλειο (Αττικής)",
  Kifissia: "Κηφισιά",
  Lamia: "Λαμία",
  Chaidari: "Χαϊδάρι",
  Stavroupoli: "Σταυρούπολη",
  Drama: "Δράμα",
  Kozani: "Κοζάνη",
  Veria: "Βέροια",
  Alimos: "Άλιμος",
  Karditsa: "Καρδίτσα",
  Polichni: "Πολίχνη",
  Pylaia: "Πυλαία",
  Ampelokipoi: "Αμπελόκηποι",
  Rethymno: "Ρέθυμνο",
  Sykies: "Συκιές",
  AnoLiosia: "Άνω Λιόσια",
  Gerakas: "Γέρακας",
  Mytilene: "Μυτιλήνη",
  Argyroupoli: "Αργυρούπολη",
  Vrilissia: "Βριλήσσια",
  AgioiAnargyroi: "Άγιοι Ανάργυροι",
  Ptolemaida: "Πτολεμαΐδα",
  Voula: "Βούλα",
  Aspropyrgos: "Ασπρόπυργος",
  Cholargos: "Χολαργός",
  Koropi: "Κορωπί",
  Corinth: "Κόρινθος",
  Corfu: "Κέρκυρα",
  Giannitsa: "Γιαννιτσά",
  Tripoli: "Τρίπολη",
  Metamorfosi: "Μεταμόρφωση",
  Kamatero: "Καματερό",
  Megara: "Μέγαρα",
  Chios: "Χίος",
  AgiaVarvara: "Αγία Βαρβάρα",
  Kaisariani: "Καισαριανή",
  EleftherioKordelio: "Ελευθέριο-Κορδελιό",
  Pyrgos: "Πύργος",
  Neapoli: "Νεάπολη",
  Perama: "Πέραμα",
  Moschato: "Μοσχάτο",
  NeaFiladelfeia: "Νέα Φιλαδέλφεια",
  Salamina: "Σαλαμίνα",
  Eleusis: "Ελευσίνα",
  Kilkis: "Κιλκίς",
  Arta: "Άρτα",
  Oraiokastro: "Ωραιόκαστρο",
  Melissia: "Μελίσσια",
  Pallini: "Παλλήνη",
  Dafni: "Δάφνη",
  Livadeia: "Λιβαδειά",
  Artemida: "Αρτέμιδα",
  Argos: "Άργος",
  Thebes: "Θήβα",
  Kos: "Κως",
  Pefki: "Πεύκη",
  Preveza: "Πρέβεζα",
  Aigio: "Αίγιο",
  Orestiada: "Ορεστιάδα",
  Thermi: "Θέρμη",
  NeaErythraia: "Νέα Ερυθραία",
  Amaliada: "Αμαλιάδα",
  NeaMakri: "Νέα Μάκρη",
  Naousa: "Νάουσα",
  Edessa: "Έδεσσα",
  Sparta: "Σπάρτη",
  Kalymnos: "Κάλυμνος",
  Ierapetra: "Ιεράπετρα",
  Panorama: "Πανόραμα",
  Florina: "Φλώρινα",
  Peraia: "Περαία",
  Vari: "Βάρη",
  Elliniko: "Ελληνικό",
  Kastoria: "Καστοριά",
  Gazi: "Γάζι",
  Paiania: "Παιανία",
  Alexandreia: "Αλεξάνδρεια",
  KalyviaThorikou: "Καλύβια Θορικού",
  Efkarpia: "Ευκαρπία",
  AgiosIoannisRenti: "Άγιος Ιωάννης Ρέντης",
  Rafina: "Ραφήνα",
  Nafplio: "Ναύπλιο",
  Tavros: "Ταύρος",
  Menemeni: "Μενεμένη",
  Missolonghi: "Μεσολόγγι",
  Papagou: "Παπάγου",
  Loutraki: "Λουτράκι",
  Drapetsona: "Δραπετσώνα",
  AgiosNikolaos: "Άγιος Νικόλαος",
  Pefka: "Πεύκα",
  NeaAlikarnassos: "Νέα Αλικαρνασσός",
  Spata: "Σπάτα",
  Nafpaktos: "Ναύπακτος",
  Ialysos: "Ιαλυσός",
  Grevena: "Γρεβενά",
  Mandra: "Μάνδρα",
  GlykaNera: "Γλυκά Νερά",
  Diavata: "Διαβατά",
  Tyrnavos: "Τύρναβος",
  Sitia: "Σητεία",
  Ermoupoli: "Ερμούπολη",
  Argostoli: "Αργοστόλι",
  NeoPsychiko: "Νέο Ψυχικό",
  AgiosStefanos: "Άγιος Στέφανος",
  Ymittos: "Υμηττός",
  Anatoli: "Ανατολή",
  Igoumenitsa: "Ηγουμενίτσα",
  NeaArtaki: "Νέα Αρτάκη",
  NeaMoudania: "Νέα Μουδανιά",
};

export const COURT_TYPES = {
  PADEL: "Padel",
  TENNIS: "Tennis",
  BASKETBALL: "Basketball",
  FOOTBALL: "Football",
} as const;

export const COURT_TYPES_GREEK = {
  Padel: "Πάντελ",
  Tennis: "Τένις",
  Basketball: "Μπάσκετ",
  Football: "Ποδόσφαιρο",
};

export const COURT_ENVIRONMENT = {
  INDOOR: "Indoor",
  OUTDOOR: "Outdoor",
} as const;

export const COURT_ENVIRONMENT_GREEK = {
  Indoor: "Εσωτερικός",
  Outdoor: "Εξωτερικός",
};

export type CourtType = (typeof COURT_TYPES)[keyof typeof COURT_TYPES];
export type CourtEnvironment = (typeof COURT_ENVIRONMENT)[keyof typeof COURT_ENVIRONMENT];
export type GreekCity = (typeof GREEK_CITIES)[keyof typeof GREEK_CITIES] | "";

// Helper function to get sorted cities for dropdown
export const getCitiesForDropdown = () => {
  return Object.keys(GREEK_CITIES)
    .sort((a, b) =>
      GREEK_CITY_DISPLAY_NAMES[a as keyof typeof GREEK_CITIES].localeCompare(
        GREEK_CITY_DISPLAY_NAMES[b as keyof typeof GREEK_CITIES],
      ),
    )
    .map((cityKey) => ({
      key: cityKey,
      displayName:
        GREEK_CITY_DISPLAY_NAMES[cityKey as keyof typeof GREEK_CITIES],
    }));
};

export const getCourtTypesForDropdown = () => {
  return Object.entries(COURT_TYPES_GREEK).map(([key, displayName]) => ({
    key,
    displayName,
  }));
};

export const getCourtEnvironmentForDropdown = () => {
  return Object.entries(COURT_ENVIRONMENT_GREEK).map(([key, displayName]) => ({
    key,
    displayName,
  }));
};

export const AVAILABLE_AMENITIES = [
  "Climate Control",
  "Premium Lighting",
  "Sound System",
  "Seating Area",
  "Natural Lighting",
  "Locker Rooms",
  "Refreshments",
  "Live Streaming",
];
