package com.example.bookacourt.enums;

import lombok.Getter;

@Getter
public enum GreekCity {
    Athens("Athens"),
    Thessaloniki("Thessaloniki"),
    Patras("Patras"),
    Piraeus("Piraeus"),
    Heraklion("Heraklion"),
    Larissa("Larissa"),
    Volos("Volos"),
    Peristeri("Peristeri"),
    Acharnes("Acharnes"),
    Kallithea("Kallithea"),
    Kalamaria("Kalamaria"),
    Glyfada("Glyfada"),
    Nikaia("Nikaia"),
    Ilion("Ilion"),
    Evosmos("Evosmos"),
    Chalandri("Chalandri"),
    Ilioupoli("Ilioupoli"),
    Keratsini("Keratsini"),
    NeaSmyrni("Nea Smyrni"),
    Marousi("Marousi"),
    AgiosDimitrios("Agios Dimitrios"),
    Zografou("Zografou"),
    Egaleo("Egaleo"),
    Ioannina("Ioannina"),
    PalaioFaliro("Palaio Faliro"),
    NeaIonia("Nea Ionia"),
    Chalcis("Chalcis"),
    AgiaParaskevi("Agia Paraskevi"),
    Trikala("Trikala"),
    Korydallos("Korydallos"),
    Petroupoli("Petroupoli"),
    Alexandroupoli("Alexandroupoli"),
    Serres("Serres"),
    Katerini("Katerini"),
    Vyronas("Vyronas"),
    Kalamata("Kalamata"),
    Xanthi("Xanthi"),
    Galatsi("Galatsi"),
    Rhodes("Rhodes"),
    Chania("Chania"),
    Komotini("Komotini"),
    Kavala("Kavala"),
    Agrinio("Agrinio"),
    Irakleio("Irakleio"),
    Kifissia("Kifissia"),
    Lamia("Lamia"),
    Chaidari("Chaidari"),
    Stavroupoli("Stavroupoli"),
    Drama("Drama"),
    Kozani("Kozani"),
    Veria("Veria"),
    Alimos("Alimos"),
    Karditsa("Karditsa"),
    Polichni("Polichni"),
    Pylaia("Pylaia"),
    Ampelokipoi("Ampelokipoi"),
    Rethymno("Rethymno"),
    Sykies("Sykies"),
    AnoLiosia("Ano Liosia"),
    Gerakas("Gerakas"),
    Mytilene("Mytilene"),
    Argyroupoli("Argyroupoli"),
    Vrilissia("Vrilissia"),
    AgioiAnargyroi("Agioi Anargyroi"),
    Ptolemaida("Ptolemaida"),
    Voula("Voula"),
    Aspropyrgos("Aspropyrgos"),
    Cholargos("Cholargos"),
    Koropi("Koropi"),
    Corinth("Corinth"),
    Corfu("Corfu"),
    Giannitsa("Giannitsa"),
    Tripoli("Tripoli"),
    Metamorfosi("Metamorfosi"),
    Kamatero("Kamatero"),
    Megara("Megara"),
    Chios("Chios"),
    AgiaVarvara("Agia Varvara"),
    Kaisariani("Kaisariani"),
    EleftherioKordelio("Eleftherio-Kordelio"),
    Pyrgos("Pyrgos"),
    Neapoli("Neapoli"),
    Perama("Perama"),
    Moschato("Moschato"),
    NeaFiladelfeia("Nea Filadelfeia"),
    Salamina("Salamina"),
    Eleusis("Eleusis"),
    Kilkis("Kilkis"),
    Arta("Arta"),
    Oraiokastro("Oraiokastro"),
    Melissia("Melissia"),
    Pallini("Pallini"),
    Dafni("Dafni"),
    Livadeia("Livadeia"),
    Artemida("Artemida"),
    Argos("Argos"),
    Thebes("Thebes"),
    Kos("Kos"),
    Pefki("Pefki"),
    Preveza("Preveza"),
    Aigio("Aigio"),
    Orestiada("Orestiada"),
    Thermi("Thermi"),
    NeaErythraia("Nea Erythraia"),
    Amaliada("Amaliada"),
    NeaMakri("Nea Makri"),
    Naousa("Naousa"),
    Edessa("Edessa"),
    Sparta("Sparta"),
    Kalymnos("Kalymnos"),
    Ierapetra("Ierapetra"),
    Panorama("Panorama"),
    Florina("Florina"),
    Peraia("Peraia"),
    Vari("Vari"),
    Elliniko("Elliniko"),
    Kastoria("Kastoria"),
    Gazi("Gazi"),
    Paiania("Paiania"),
    Alexandreia("Alexandreia"),
    KalyviaThorikou("Kalyvia Thorikou"),
    Efkarpia("Efkarpia"),
    AgiosIoannisRenti("Agios Ioannis Renti"),
    Rafina("Rafina"),
    Nafplio("Nafplio"),
    Tavros("Tavros"),
    Menemeni("Menemeni"),
    Missolonghi("Missolonghi"),
    Papagou("Papagou"),
    Loutraki("Loutraki"),
    Drapetsona("Drapetsona"),
    AgiosNikolaos("Agios Nikolaos"),
    Pefka("Pefka"),
    NeaAlikarnassos("Nea Alikarnassos"),
    Spata("Spata"),
    Nafpaktos("Nafpaktos"),
    Ialysos("Ialysos"),
    Grevena("Grevena"),
    Mandra("Mandra"),
    GlykaNera("Glyka Nera"),
    Diavata("Diavata"),
    Tyrnavos("Tyrnavos"),
    Sitia("Sitia"),
    Ermoupoli("Ermoupoli"),
    Argostoli("Argostoli"),
    NeoPsychiko("Neo Psychiko"),
    AgiosStefanos("Agios Stefanos"),
    Ymittos("Ymittos"),
    Anatoli("Anatoli"),
    Igoumenitsa("Igoumenitsa"),
    NeaArtaki("Nea Artaki"),
    NeaMoudania("Nea Moudania");

    private final String displayName;

    GreekCity(String displayName) {
        this.displayName = displayName;
    }

}